/**
 * Safety number (fingerprint) generation for key verification
 * 
 * Safety numbers allow users to verify that they're communicating with
 * the intended recipient and not a man-in-the-middle attacker. The safety
 * number is a cryptographic hash of both users' public keys.
 * 
 * Inspired by Signal's safety number implementation.
 */

import { sha256 } from '@noble/hashes/sha256';
import { bytesToHex } from './utils.js';

/**
 * Generate a safety number (fingerprint) from two public keys
 * 
 * The safety number is generated by:
 * 1. Sorting the two public keys lexicographically to ensure consistent ordering
 * 2. Concatenating them
 * 3. Hashing with SHA-256
 * 4. Formatting as a readable string (groups of 5 digits)
 * 
 * Both users in a conversation will generate the same safety number,
 * allowing them to verify they have each other's correct public keys.
 * 
 * @param publicKey1 - First user's X25519 public key
 * @param publicKey2 - Second user's X25519 public key
 * @returns Safety number as a formatted string (e.g., "12345 67890 11121 31415 16171 81920")
 * 
 * @example
 * ```typescript
 * const safetyNumber = generateSafetyNumber(alicePublicKey, bobPublicKey);
 * // Both Alice and Bob will generate the same safety number
 * ```
 */
export function generateSafetyNumber(
  publicKey1: Uint8Array,
  publicKey2: Uint8Array
): string {
  // Validate inputs
  if (!(publicKey1 instanceof Uint8Array) || publicKey1.length !== 32) {
    throw new Error('publicKey1 must be a 32-byte Uint8Array');
  }
  if (!(publicKey2 instanceof Uint8Array) || publicKey2.length !== 32) {
    throw new Error('publicKey2 must be a 32-byte Uint8Array');
  }
  
  // Sort keys lexicographically to ensure consistent ordering
  const hex1 = bytesToHex(publicKey1);
  const hex2 = bytesToHex(publicKey2);
  
  const [first, second] = hex1 < hex2
    ? [publicKey1, publicKey2]
    : [publicKey2, publicKey1];
  
  // Concatenate the sorted keys
  const combined = new Uint8Array(64);
  combined.set(first, 0);
  combined.set(second, 32);
  
  // Hash with SHA-256
  const hash = sha256(combined);
  
  // Convert to a readable numeric string
  // Use first 60 bits (7.5 bytes) to generate a 18-digit number
  // This gives us enough entropy while keeping it readable
  const numericString = formatHashAsNumericString(hash);
  
  return numericString;
}

/**
 * Format a hash as a readable numeric string
 * 
 * Takes the first 60 bits of the hash and formats it as
 * groups of 5 digits for readability.
 * 
 * @param hash - SHA-256 hash (32 bytes)
 * @returns Formatted numeric string (e.g., "12345 67890 11121 31415 16171 81920")
 */
function formatHashAsNumericString(hash: Uint8Array): string {
  // Use first 8 bytes (64 bits) of the hash
  const view = new DataView(hash.buffer, hash.byteOffset, 8);
  const num = view.getBigUint64(0, false); // big-endian
  
  // Convert to string and take first 30 digits (for nice formatting)
  let numStr = num.toString();
  
  // Pad with zeros if needed
  while (numStr.length < 30) {
    numStr = '0' + numStr;
  }
  
  // Take first 30 digits
  numStr = numStr.slice(0, 30);
  
  // Format as groups of 5 digits
  const groups: string[] = [];
  for (let i = 0; i < numStr.length; i += 5) {
    groups.push(numStr.slice(i, i + 5));
  }
  
  return groups.join(' ');
}

/**
 * Generate a compact safety number (shorter version for display)
 * 
 * This generates a shorter 12-digit safety number for situations
 * where space is limited. Less secure than the full version but
 * still provides reasonable verification.
 * 
 * @param publicKey1 - First user's X25519 public key
 * @param publicKey2 - Second user's X25519 public key
 * @returns Compact safety number (e.g., "12345 67890 12")
 */
export function generateCompactSafetyNumber(
  publicKey1: Uint8Array,
  publicKey2: Uint8Array
): string {
  const fullSafetyNumber = generateSafetyNumber(publicKey1, publicKey2);
  // Take first 12 digits
  const compact = fullSafetyNumber.replace(/\s/g, '').slice(0, 12);
  // Format as 3 groups of 4 digits
  return `${compact.slice(0, 4)} ${compact.slice(4, 8)} ${compact.slice(8, 12)}`;
}

/**
 * Verify that a safety number matches the expected value
 * 
 * @param publicKey1 - First user's X25519 public key
 * @param publicKey2 - Second user's X25519 public key
 * @param expectedSafetyNumber - The safety number to verify against
 * @returns True if the safety numbers match
 */
export function verifySafetyNumber(
  publicKey1: Uint8Array,
  publicKey2: Uint8Array,
  expectedSafetyNumber: string
): boolean {
  const actualSafetyNumber = generateSafetyNumber(publicKey1, publicKey2);
  // Normalize by removing spaces for comparison
  const actual = actualSafetyNumber.replace(/\s/g, '');
  const expected = expectedSafetyNumber.replace(/\s/g, '');
  return actual === expected;
}

/**
 * Generate a QR code-friendly version of the safety number
 * 
 * Returns a JSON string that can be encoded as a QR code for
 * easy verification by scanning.
 * 
 * @param publicKey1 - First user's X25519 public key (local user)
 * @param publicKey2 - Second user's X25519 public key (remote user)
 * @param userId1 - First user's ID
 * @param userId2 - Second user's ID
 * @returns JSON string for QR code encoding
 */
export function generateQRCodeData(
  publicKey1: Uint8Array,
  publicKey2: Uint8Array,
  userId1: string,
  userId2: string
): string {
  const safetyNumber = generateSafetyNumber(publicKey1, publicKey2);
  
  return JSON.stringify({
    v: 1, // version
    users: [userId1, userId2].sort(), // sorted for consistency
    safety: safetyNumber.replace(/\s/g, ''), // no spaces for compactness
  });
}

/**
 * Parse QR code data and verify it matches expected values
 * 
 * @param qrData - JSON string from scanned QR code
 * @param expectedUserId1 - Expected first user ID
 * @param expectedUserId2 - Expected second user ID
 * @param expectedPublicKey1 - Expected first user's public key
 * @param expectedPublicKey2 - Expected second user's public key
 * @returns Object with verification result and safety number
 */
export function verifyQRCodeData(
  qrData: string,
  expectedUserId1: string,
  expectedUserId2: string,
  expectedPublicKey1: Uint8Array,
  expectedPublicKey2: Uint8Array
): { valid: boolean; safetyNumber?: string; error?: string } {
  try {
    const data = JSON.parse(qrData);
    
    // Validate structure
    if (data.v !== 1) {
      return { valid: false, error: 'Unsupported QR code version' };
    }
    
    if (!Array.isArray(data.users) || data.users.length !== 2) {
      return { valid: false, error: 'Invalid user list in QR code' };
    }
    
    if (typeof data.safety !== 'string') {
      return { valid: false, error: 'Invalid safety number in QR code' };
    }
    
    // Verify user IDs match (order-independent)
    const sortedExpected = [expectedUserId1, expectedUserId2].sort();
    const sortedActual = data.users.slice().sort();
    
    if (sortedExpected[0] !== sortedActual[0] || sortedExpected[1] !== sortedActual[1]) {
      return { valid: false, error: 'User IDs do not match' };
    }
    
    // Generate expected safety number
    const expectedSafetyNumber = generateSafetyNumber(expectedPublicKey1, expectedPublicKey2);
    const expectedCompact = expectedSafetyNumber.replace(/\s/g, '');
    
    // Compare safety numbers
    if (data.safety !== expectedCompact) {
      return { valid: false, error: 'Safety numbers do not match' };
    }
    
    // Format safety number with spaces for display
    const formatted = expectedSafetyNumber;
    
    return { valid: true, safetyNumber: formatted };
  } catch (error) {
    return { valid: false, error: 'Failed to parse QR code data' };
  }
}
